CREATE TABLE IF NOT EXISTS shareit_user
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255)                            NOT NULL,
    email VARCHAR(512)                            NOT NULL,
    CONSTRAINT user_pk PRIMARY KEY (id),
    CONSTRAINT UQ_user_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS item
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    description VARCHAR(255)                            NOT NULL,
    available   BOOLEAN                                 NOT NULL,
    id_user     BIGINT                                  NOT NULL,
    id_request  BIGINT,
    CONSTRAINT item_pk PRIMARY KEY (id),
    CONSTRAINT user_id_fk FOREIGN KEY (id_user) REFERENCES shareit_user (id),
    CONSTRAINT request_id_fk FOREIGN KEY (id_request) REFERENCES requests (id)
);

CREATE TABLE IF NOT EXISTS booking
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_item            BIGINT                                  NOT NULL,
    start_time_booking TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    end_time_booking   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    id_user            BIGINT                                  NOT NULL,
    status_booking     VARCHAR(255)                            NOT NULL,
    CONSTRAINT booking_pk PRIMARY KEY (id),
    CONSTRAINT user_booking_id_fk FOREIGN KEY (id_user) REFERENCES shareit_user (id),
    CONSTRAINT item_id_fk FOREIGN KEY (id_item) REFERENCES item (id)
);

CREATE TABLE IF NOT EXISTS comments
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_item BIGINT                                  NOT NULL,
    text    VARCHAR(512)                            NOT NULL,
    author  BIGINT                                  NOT NULL,
    created TIMESTAMP WITHOUT TIME ZONE             NOT NULL
);


CREATE TABLE IF NOT EXISTS requests
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description  VARCHAR(512)                            NOT NULL,
    requestor_id BIGINT                                  NOT NULL,
    created      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT request_pk PRIMARY KEY (id),
    CONSTRAINT user_request_fk FOREIGN KEY (requestor_id) REFERENCES shareit_user (id)
);